container:
  image: ubuntu:latest
  cpu: 8
  memory: 16G

build_toolchain_task:
  env: 
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get update
    - apt-get -y install build-essential jq bash cmake git gawk grep curl xz-utils make texinfo automake autotools-dev autoconf-archive
    - cp Meta/Build/example_config.json ./Factory/config.json
    - ./Factory/setup_env.sh
