compute_engine_instance:
  platform: linux
  cpu: 8
  memory: 16G
  disk: 100

container:
  image: ubuntu:latest

dependencies_task:
  env: 
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get update
    - apt-get -y install build-essential jq bash cmake git gawk grep

build_toolchain_task:
  depends_on:
    - dependencies
  script: ./Factory/set_env.sh